# Generated by Django 3.2.9 on 2021-12-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_registeruser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='gender',
        ),
    ]
