# Generated by Django 3.2.9 on 2021-12-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_registeruser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='contact',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
