# Generated by Django 3.2.9 on 2021-12-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_registeruser_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='gender',
            field=models.CharField(default='ND', max_length=11),
            preserve_default=False,
        ),
    ]
