# Generated by Django 3.2.9 on 2021-12-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_registeruser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='userQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('imgupload', models.FileField(upload_to='UploadedFile')),
                ('description', models.TextField()),
            ],
        ),
    ]
