# Generated by Django 3.2.9 on 2021-12-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_registeruser_queriedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='queriedBy',
        ),
        migrations.AddField(
            model_name='userquestion',
            name='queriedBy',
            field=models.CharField(default='NA', max_length=30),
            preserve_default=False,
        ),
    ]
