# Generated by Django 3.2.9 on 2022-01-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20211222_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='fileupload',
            field=models.FileField(null=True, upload_to='UploadedFile'),
        ),
    ]
