# Generated by Django 3.2.9 on 2022-01-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_userquestion_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
