# Generated by Django 3.2.9 on 2022-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_registeruser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='ProfileImages'),
        ),
    ]
