# Generated by Django 3.2.9 on 2022-02-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_registeruser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='ProfileImages'),
        ),
    ]
