# Generated by Django 3.2.9 on 2022-02-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_remove_registeruser_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='cnfpswd',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
