# Generated by Django 3.2.9 on 2022-02-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20220204_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='contact',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
